#ifndef PROJECT_WEATHER__PRECIPITATION_PRINTING_H
#define PROJECT_WEATHER__PRECIPITATION_PRINTING_H

#include "weather.h"

void PrintPrecipitation(FILE *output_file, WEATHER* weather);

#endif //PROJECT_WEATHER__PRECIPITATION_PRINTING_H
